

Figure\ \@ref(fig:ZMEExamples) shows some probability functions for a zero-modified *exponential* distribution; Fig.\ \@ref(fig:ZMGExamples) shows some probability functions for a zero-modified *gamma* distribution.


```{r ZMEExamples, echo=FALSE, fig.align="center", fig.cap="Zero-modified exponential distributions.", fig.width=8, fig.height=4, out.width="90%"}

###  Set up  ###
p <- 0.55
x.rate = 1.5

x <- seq(0, 3,
         length = 100)
y <-  (1 - p) * dexp(x, 
                     rate = x.rate)
                     

par( mfrow = c(1, 2))

###  Plots  ###

plot(y ~ x,
     type = "l",
     axes = FALSE,
     ylim = c(0,
              max( c(y, 1 - p) ) ),
     xlab = expression(italic(X)),
     ylab = expression(Prob.~"function"),
     main = expression(bold(Zero*"-"*modified~exponential)),
     lwd = 3)
abline(h = 0,
       col = "grey")
axis(side = 1)
axis(side = 2,
     at = c(0, 
            p),
     las = 2)
box()

points(x = 0, # Included
       y = p,
       pch = 19)

# Explanatory labels
arrows(x0 = 0.35,
       x1 = 0,
       y0 = 0.17,
       y1 = p,
       length = 0.15,
       angle = 15)
text(x = 0.35,
     y = 0.17,
     pos = 1,
     label = expression(Pr*"("*italic(X)==0*")" ) )


arrows(x0 = 1.5,
       x1 = 1,
       y0 = 0.6,
       y1 = dexp(x = 1, 
                 rate = x.rate) * (1 - p),
       length = 0.15,
       angle = 15)
text(x = 1.5,
     y = 0.6,
     pos = 3,
     label = expression( Exponential~distribution) )




###

p <- 0.65
x.rate = 4

x <- seq(0, 3,
         length = 100)
y <-  (1- p) * dexp(x, 
                    rate = x.rate)

plot(y ~ x,
     type = "l",
     axes = FALSE,
     ylim = c(0,
              max( c(y, p) ) ),
     xlab = expression(italic(X)),
     ylab = expression(Prob.~"function"),
     main = expression(bold(Zero*"-"*modified~exponential)),
     lwd = 3)
abline(h = 0,
       col = "grey")
axis(side = 1)
axis(side = 2,
     at = c(0, 
            p),
     las = 2)
box()

points(x = 0, # Included
       y = p,
       pch = 19)




p <- 0.25
x.rate = 2

x <- seq(0, 3,
         length = 100)
y <-  (1 -p) * dexp(x, 
                    rate = x.rate)
axis(side = 2,
     at = c(0, 
            p),
     las = 2)
lines(y ~ x,
      lwd = 3,
      lty = 2)
points(x = 0, # Included
       y = p,
       lwd = 3,
       pch = 4)

legend("topright",
       lwd = 2,
       pch = c(19, 4),
       lty = c(1, 2),
       bty = "n",
       legend = c(expression(italic(p)==0.65~and~lambda==4),
                  expression(italic(p)==0.25~and~lambda==2)))

```





```{r ZMGExamples, echo=FALSE, fig.align="center", fig.cap="Zero-modified gamma distributions.", fig.width=8, fig.height=4, out.width="90%"}

###  Set up  ###
p <- 0.4

alpha <- 1.5
beta  <- 0.5

x <- seq(0, 2.5,
         length = 100)
y <-  (1 - p) * dgamma(x, 
                     shape = alpha,
                     scale = beta)
                     

par( mfrow = c(1, 2))

###  Plots  ###

plot(y ~ x,
     type = "l",
     axes = FALSE,
     ylim = c(0,
              max( c(y, 1 - p) ) ),
     xlab = expression(italic(X)),
     ylab = expression(Prob.~"function"),
     main = expression(bold(Zero*"-"*modified~"gamma")),
     lwd = 3)
abline(h = 0,
       col = "grey")
axis(side = 1)
axis(side = 2,
     at = c(0, 
            p),
     las = 2)
box()

points(x = 0, # Included
       y = p,
       pch = 19)

# Explanatory labels
arrows(x0 = 0.5,
       x1 = 0,
       y0 = 0.17,
       y1 = p,
       length = 0.15,
       angle = 15)
text(x = 0.5,
     y = 0.17,
     pos = 1,
     label = expression(Pr*"("*italic(X)==0*")" ) )


arrows(x0 = 1.5,
       x1 = 1,
       y0 = 0.5,
       y1 = dgamma(x = 1, 
                   shape = alpha,
                   scale = beta) * (1 - p),
       length = 0.15,
       angle = 15)
text(x = 1.5,
     y = 0.5,
     pos = 3,
     label = expression( "Gamma"~distribution) )




###

p <- 0.2
alpha <- 1.5
beta  <- 1.8

x <- seq(0, 10,
         length = 100)
y <-  (1 - p) * dgamma(x, 
                       shape = alpha,
                       scale = beta)

plot(y ~ x,
     type = "l",
     axes = FALSE,
     ylim = c(0,
              0.3 ),
     xlab = expression(italic(X)),
     ylab = expression(Prob.~"function"),
     main = expression(bold(Zero*"-"*modified~"gamma")),
     lwd = 3)
abline(h = 0,
       col = "grey")
axis(side = 1)
axis(side = 2,
     at = c(0, 
            p),
     las = 2)
box()

points(x = 0, # Included
       y = p,
       pch = 19)


###

p <- 0.15
alpha <- 2.5
beta  <- 1.2

y <-  (1 -p) * dgamma(x, 
                      shape = alpha,
                      scale = beta)
axis(side = 2,
     at = p,
     las = 2)
lines(y ~ x,
      lwd = 3,
      lty = 2)
points(x = 0, # Included
       y = p,
       lwd = 3,
       pch = 4)

legend("topright",
       lwd = 2,
       pch = c(19, 4),
       lty = c(1, 2),
       bty = "n",
       legend = c(expression(italic(p)==0.2*","~alpha==1.5*","~beta==1.8),
                  expression(italic(p)==0.15*","~alpha==2.5*","~beta==1.2)))

```

