# Mixed distributions {#MixedDistributions}

::: {.objectivesBox .objectives data-latex="{iconmonstr-target-4-240.png}"}
On completion of this module, you should be able to:

* recognise the probability functions and underlying parameters of mixed variables.
* know the basic properties of the above mixed distributions.
* apply these distributions as appropriate to problem solving.
:::



## Hurdle models {#HurdleModels}

A point mass at\ $0$, plus truncated distribution for positive values.

* Not censoring
Concept: Two-stage model:

First, a Bernoulli model decides whether the value is zero or positive.

Then, a truncated distribution (e.g., Poisson or Gamma) is fitted to the positive values only.

* Two-part model: Bernoulli + truncated distn (e.g., gamma).
* Healthcare costs; heavy zero mass
* Helpful with structural zeroes
* Model:
$$
   f_X(x) = 
   \begin{cases}
      p              & \text{if $X = 0$}\\
      (1 - p) g_X(x) & \text{if $x > 0$,}
   \end{cases}
$$
where $g_X(x)$ is continuous distribution defined in $x\in\mathbb{R}_{+}$.


:::{.example #HurdleExample name="Hurdle model"}
Using a normal distribution for $g_X(x)$,
$$
  f_X(x) = 
    \begin{cases}
       p              & \text{if $X = 0$}\\
       (1 - p) g_X(x) & \text{if $x > 0$,}
    \end{cases}
$$
where $g_X(x)$ is the normal distribution.
:::


## Tobit model {#CensoredModels}

A censored normal: positive mass at a threshold (e.g.,\ $0$), plus continuous above it.

Concept: A censored regression model, used when there's an underlying latent continuous variable that’s only partially observed.


* Joint model
* Censored economic data; wages; Time use (Jude Brown)
* Model:

Assume some *latent variable*, say\ $z$, such that $z\in\mathbb{R}$, with probability function $f_Z(z)$.
When $Z < z^*$, the value of\ $z$ is recorded as\ $Z = z*$.
Usually $z^* = 0$, so that any value of\ $Z \le 0$ is recorded as\ $z = 0$.
That is, we observe the random variable\ $X$ such that
$$
  X = 
  \begin{cases}
    ??   & \text{if $Z \le z^*$};\\
    X^*  & \text{if $Z > z^*$}. 
  \end{cases}
$$


:::{.example #TobitExample name="Cnnsoring/Tobit model???"}
Consider a latent variable\ $Z$, so that the values $Z < 0$ are recorded as\ $Z = 0$, and where
$$
  Z \sim N(\mu, signma^2).
$$.
Then, define the random variable\ $X$ as FIX!!
$$
  X = 
  \begin{cases}
    \Phi(z*)   & \text{if $X = 0$};\\
    X^*        & \text{if $X > 0^*$}. 
  \end{cases}
$$
:::




## Poisson sums of gamma distributions: Poisson-gamma distributions {#TweedieModels}

* One part model
* Rainfall, insurance claims
* Single model


Poisson--gamma distribution take a different approach, but mixed data as a Poisson sum of independent gamma distributions.
Suppose the number of discrete events is\ $N$, such that
$$
  N \sim \text{Pois}(\lambda).
$$
That is, an event occurs\ $N$ times.
Then, for $i = 1, 2, \dots, N$, a continuous random variable is observed, say\ $Y_i$, such that
$$
   Y_i \sim \text{Gamma}(\alpha_i, \beta).
$$
If $N = 0$, then no events, $Y_i$ are observed at all; however, if $N > 0$ then
$$
  X = \sum_{i = 1}^N Y_i
$$
has a continuous distribution.
Combining, the distribution of\ $X$ is
$$
  X = 
  \begin{cases}
    exp(-\lambda) & \text{if $X = 0$}\\
    ???           & \text{if $x > 0$}
  \end{cases}
$$
The distribution of\ $X$ has a *Poisson--gamma* distribution.
The distribution of\ $X$ cannot be written in a closed form (except for special cases), but it can be shown (POINT) that
$$
  \operatorname{E}[X] = \mu = ?? \quad\text{and}\quad \operatorname{var}[X] = \phi \mu*p.
$$

Construction:

Let
$$
  N \sim \text{Poisson}(\lambda)
  \quad\text{and}\quad
  Y_i \sim \text{Gamma}(\alpha, \beta).
$$
Then, 
$$
  Y = \sum_{i = 1}^N Y_i,
$$
and so $\Pr(Y = 0) = \Pr(N = 0)$.



:::{.example #RainfallModelling name="Modelling monthly rainfall}
Modelling rainfall. 
Using hurdle from Chandler and Wheater? Tobit thing from ISWM, and Poisson--gamma, 
:::


## Exercises


Selected answers appear in Sect.\ \@ref(AnswersChapUnknownAsYet).


:::{.exercise #ex1}
Exercise 1
:::

