\part{Appendices}

# (APPENDIX) Appendices {-}



# Some useful series {#UsefulSeries}

For convenience and reference we state some results here involving series that occur quite frequently in probability and statistical theory.


## Finite series

* Sum of natural numbers:
\begin{equation}
   1 + 2 + 3 + \ldots + n 
   = \frac{n(n + 1)}{2}.
   (\#eq:SumNaturalNumbers)
\end{equation}

* Sum of squares of natural numbers:
\begin{equation}
   1^2 + 2^2 + 3^2 + \ldots + n^2
   = \frac{n}{6}(n + 1)(2n + 1)
   (\#eq:SumSquaredNaturalNumbers)
 \end{equation}
 
* Geometric series
\begin{align}
   a + ar + ar^2 + \ldots + ar^{n - 1}
   &= \frac{a(1 - r^n)}{1 - r}
   (\#eq:SumGeometricFinite)\\
   &\rightarrow \frac{a}{1 - r} \text{ as $n  \rightarrow  \infty$}
  (\#eq:SumGeometricInfinite)
\end{align}
where the infinite series only converges if $|r| < 1$.

* Binomial expansion:
\begin{equation}
   (a + b)^n = b^n + {n \choose 1}ab^{n - 1} + \ldots + {n \choose r}a^r b^{n - r} + \ldots a^n.
   (\#eq:BinomialSeries)
\end{equation}



## Power series

A power series is a series of the form $\sum_{n = 0}^{\infty}a_n z^n$.

* Exponential function:
\begin{align}
   e^z
   &= 1 + z + \frac{z^2}{2!} + \frac{z^3}{3!} + \ldots
   (\#eq:Exponential)\\
   e^{-z}
   &= 1 - z + \frac{z^2}{2!} - \frac{z^3}{3!} + \ldots
   (\#eq:ExponentialNegative)
\end{align}

* Logarithmic series:
\begin{align}
   \log(1 + z)
   &= z - \frac{z^2}{2} + \frac{z^3}{3} - \ldots
   (\#eq:Logarithmic)\\
   \log(1 - z)
   &= -z - \frac{z^2}{2} - \frac{z^3}{3} - \ldots
   (\#eq:LogarithmicNegative)
\end{align}

* Others:
\begin{align}
   (1 - z)^{-1}
   &= 1 + z + z^2 + z^3 + \ldots
   (\#eq:Other1)\\
   (1 - z)^{-r}
   &= 1 + rz + \frac{r(r + 1)z^2}{2!} + \frac{r(r + 1)(r + 2)z^3}{3!} + \ldots
   (\#eq:Other2)
\end{align}
Note that the expressions on the RHS above do not converge to the LHS for all values of $z$.

DOES THIS COMMENT APPLY TO ALL????



# Using R with univariate distributions {#UseRDistributions}

In **R**, standard distributions have four associated function:

* Computing the [probability function](#ProbabilityFunction): All begin with `p` (such as `pnorm()` for the normal distribution).
* Computing the [distribution function](DistributionFunction): All begin with `d`(such as `dnorm()`).
* Compiting the quantile function (XREF): All begin with `q` (such as `qnorm()`).
* Generating random numbers (XREF): All begin with `r` (such as `rnorm()`).

ADD PARAMETERS TOO... if enough room.

In **R**, four function are available for most distributions

* Computing the [probability function](#ProbabilityFunction): Functions start with `d`
* Computing the [distribution function](#DistributionFunction): Functions start with `p`
* Computing the quantiles: Functions start with `q`
* Generatimg random numbers: Functions start with `r`.

For example, the fours function above are called, for the normal distribution (denoted `norm` in **R**):

* `dnorm()`
* `pnorm()`
* `qnorm()`
* `rnorm()`

>>>>>>> f5d2c127824fb49c2c5b9061a8dd86e144cb85ee

ADD a chapter on how to generate random numbers and quantiles and so on.


<<<<<<< HEAD
## Standard univariate discrete distributions
=======
## Discrete distributions

Distribution       | **R** function          | Common parameters
-------------------|-------------------------|-----------------------
Discrete uniform   | `sample()`              | ~                     
Binomial           | `dbinom(x, size, prob)` | `x`:  Values where to evaluate the probability function
.                  | `pbinom(q, size, prob)` | `q`: Quantiles
.                  | `qbinom(p, size, prob)` | `p`: Probabilities
.                  | `rbinom(n, size, prob)` | `n`: The number of random observations to generate
.                  |  .                      | `size`: The number of trials
.                  |  .                      | `prob`: The probability of 'success' in each trial
Poisson            | `dpois(x, lambda)`      | `x`: Values where to evaluate the probability function  
.                  | `ppois(q, lambda)`      | `q`: Quantiles
.                  | `qpois(p, lambda)`      | `p`: Probabilities
.                  | `rpois(n, lambda)`      | `n`: The number of random observations to generate
.                  |  .                      | `lambda`: The Poisson mean
Geometric          | `dgeom(x, prob)`        | `x`: Values where to evaluate the probability function  
.                  | `pgeom(q, prob)`        | `q`: Quantiles
.                  | `qgeom(p. prob)`        | `p`: Probabilities   
.                  | `rgeom(n, prob)`        | `n`: The number of random observations to generate
.                  |  .                      | `prob`: The probability of 'success' in each trial
Negative binomial  | `dnbinom(x, size, prob, mu)` | `x`: Values where to evaluate the probability function          
.                  | `pnbinom(q, size, prob, mu)` | `q`: Quantiles
.                  | `qnbinom(p, size, prob, mu)` | `p`: Probabilities   
.                  | `rnbinom(p, size, prob, mu)` | `n`: The number of random observations to generate
.                  |  .                           | `size`: The number of trials
.                  |  .                           | `prob`: The probability of 'success' in each trial
.                  |  .                           | `mu`: Useful for alternative parameterisation


## Continuous distributions


Distribution       | Probability function | Distribution function | Quantile function     | Random numbers
-------------------|----------------------|-----------------------|-----------------------|-----------------
Discrete uniform   | `sample()`           | ~                     |   ~                   | ~
Binomial           | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Poisson            | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Geometric          | `dgeom()`            | `pgeom()`             | `qunif()`             | `runif()`
Negative binomial  | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Continuous uniform | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Normal|            | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Gamma|             | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
$t$                | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
$\chi$-squared     | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
$F$                | `dunif()`            | `punif()`             | `qunif()`             | `runif()`



## Multivariate distributions 

ADD??




Distribution       | Probability function | Distribution function | Quantile function     | Random numbers
-------------------|----------------------|-----------------------|-----------------------|-----------------
Discrete uniform   | `sample()`           | ~                     |   ~                   | ~
Binomial           | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Poisson            | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Geometric          | `dgeom()`            | `pgeom()`             | `qunif()`             | `runif()`
Negative binomial  | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Continuous uniform | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Normal|            | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
Gamma|             | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
$t$                | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
$\chi$-squared     | `dunif()`            | `punif()`             | `qunif()`             | `runif()`
$F$                | `dunif()`            | `punif()`             | `qunif()`             | `runif()`


>>>>>>> f5d2c127824fb49c2c5b9061a8dd86e144cb85ee

Distribution       | **R**  functions (with common parameter)
------------------------------------------------------------------------------------------------
Discrete uniform   | Random sample: `sample()`  
Binomial           | `dbinom(x, size, prob)`   
                   | `pbinom(q, size, prob)`  
                   | `qbinom(p, size, prob)`  
                   | `rbinom(n, size, prob)`
Poisson            | `dpois(x, lambda)`   
                   | `ppois(q, lambda)`   
                   | `qpois(p, lambda)`   
                   | `rpois(n, lambda)`
Geometric          | `dgeom(x, prob)`   
                   | `pgeom(q, prob)`   
                   | `qgeom(p, prob)`   
                   | `rgeom(n, prob)`
Negative binomial  | `dnbinom(x, size, prob, mu)` 
                   | `pnbinom(q, size, prob, mu)` 
                   | `qdbinom(p, size, prob, mu)` 
                   | `rnbinom(n, size, prob, mu)`
                   

## Standard univariate continuous distributions
                 
                   
Distribution       | **R**  functions (with common parameter)
------------------------------------------------------------------------------------------------
Continuous uniform | `dunif(x, min = 0, max = 1)`   
                   | `punif(q, min = 0, max = 1)`   
                   | `qunif(p, min = 0, max = 1)`   
                   | `runif(r, min = 0, max = 1)`
Normal             | `dnorm(x, mean = 0, sd = 1)`   
                   | `pnorm(q, mean = 0, sd = 1)`   
                   | `qnorm(p, mean = 0, sd = 1)`   
                   | `rnorm(n, mean = 0, sd = 1)`
Gamma              | `dgamma(x, shape, rate = 1, scale = 1 / rate)`  
                   | `pgamma(q, shape, rate = 1, scale = 1 / rate)`  
                   | `qgamma(p, shape, rate = 1, scale = 1 / rate)`  
                   | `rgamma(n, shape, rate = 1, scale = 1 / rate)`
$t$                | `dt(x, df)`      
                   | `pt(q, df)`      
                   | `qt(p, df)`      
                   | `rt(n, df)`
$\chi$-squared     | `dchisq(x, df)`  
                   | `pchisq(q, df)`  
                   | `qchisq(p, df)`  
                   | `rchisq(n, df)`
$F$                | `df(x, df1, df2)`      
                   | `pf(q, df1, df2)`      
                   | `qf(p, df1, df2)`      
                   | `rf(n, df1, df2)`



## Standard bivariate distributions

Add `mvtnorm::dmvnor()`???



# Solutions

## Answers for Chap. 1

:::{.answer}
Answer to Exercise \@ref(exr:BasicProbs)

1. $0.11$
2. $0.24$
3. $0.32$
4. $0.11/0.35$
5. $\Pr(A) \times \Pr(B) = 0.44\times 0.35 = 0.154 \ne \Pr(A\cap B) = 0.11$; not independent.
:::

:::{.answer}
Answer to Exercise \@ref(exr:Quadratic).

* $S = \{ (a,b,c) \mid a\in(-\infty, 0)\cap (0, \infty), -\infty < b < \infty, -\infty < c < \infty\}$.
* The solutions to a quadratic equation are given by
\[
   x = \frac{-b \pm \sqrt{b^2 - 4ac} }{2a}.
\]
For two equal roots, $b^2 - 4ac = 0$, so event $A$ is defined as $A = \{ (a,b,c) \mid b^2 - 4ac = 0\}$.
:::




## Answers for Chap. 2



## Answers for Chap. 3

:::{.answer}
Answer to Exercise \@ref(exr:Cauchy).

1. See Fig. \@ref(fig:Cauchy) (left panel).
1. Evaluate $F_X(t) = \displaystyle \int_{-\infty}^t \frac{1}{\pi(1 + x^2)}\,dx = \frac{1}{\pi}\arctan(x) + \frac{1}{2}$.
   See Fig. \@ref(fig:Cauchy) (right panel).
1. $\displaystyle \text{E}(X) =  \int_{-\infty}^t \frac{x}{\pi(1 + x^2)}\,dx = ...$, which is not defined.
:::

```{r Cauchy, fig.align="center", fig.cap="The Cauchy distribution"}
par( mfrow = c(1, 2))
x <- seq(-5, 5,
         length = 100)
y <- 1 / (pi * (1 + x^2))
plot(y ~ x,
     lwd = 2,
     las = 1,
     type = "l",
     main = "Density function for\nthe Cauchy distribution",
     xlab = "X",
     ylab = "Density function")

Y <- atan(x)/pi + 0.5
plot(Y ~ x,
     lwd = 2,
     las = 1,
     ylim = c(0, 1),
     type = "l",
     main = "Distribution function for\nthe Cauchy distribution",
     xlab = "X",
     ylab = "Distribution function")
```



## Answers for Chap. 4



## Answers for Chap. 5



## Answers for Chap. 6



## Answers for Chap. 7



## Answers for Chap. 8

