## Answers for Chap. 7

:::{.answer}
**Answer to Exercise \@ref(exr:Ycubed).**

For $0 < x < 2$, the transformation is one-to-one.
The inverse transform is $X = Y^{1/3}$, and so $0 < y < 8$.

1. $F_Y(y) = \Pr(Y\le y)
   = \Pr(X^3 \le y) = \Pr(X\le y^{1/3}) = F_X( y^{1/3})
   = \int_{u = 0}^{y^{1/3}} u/2\,du = u^2/4\Big|_{u = 0}^{u = y^{1/3}} = y^{2/3}/4.$
Differentiate to find the pdf: 
$\frac{d}{dy} y^{2/3}/4 = y^{-1/3}/6$. 
The pdf of $Y$ is

\[
   f_Y(y) = \begin{cases}
               y^{-1/3}/6 & \text{for $0 < y < 8$};\\
               0 & \text{otherwise}.
            \end{cases}
\]

2. Since $w(y) = y^{1/3}$, then $w'(y) = y^{-2/3}$.
Then:  
\begin{align*}
   f_Y(y)
   &= f_X(y) |J|\\
   &= y^{1/3}/2 \times \overbrace{y^{-2/3}/3}^{|J|} \\
   &= y^{-1/3}/6.
\end{align*}
So the pdf of $Y$ is as above.
:::


:::{.answer}
**Answer to Exercise \@ref(exr:JointDiscrete).**

Note $Y_1$ takes the values $1$ and $2$ for $Y_2 = 0$;
$Y_1$ takes the values $2$ and $3$ for $Y_2 = 1$.

The joint pf is shown in Table \@ref(tab:JDTable).
Hence,

\[
   f_{Y_1} = 
   \begin{cases} 
      2/14 & \text{if $y_1 = 1$};\\
      7/14 & \text{if $y_1 = 2$};\\
      5/14 & \text{if $y_1 = 3$};\\
      0    & \text{otherwise}.
    \end{cases}
\]

```{r JDTable, echo=FALSE}
JDTable <- array( dim = c(2, 4))

colnames(JDTable) <- c("",
                       "$Y_1 = 1$",
                       "$Y_1 = 2$",
                       "$Y_1 = 3$")
JDTable[1, ] <- c("$Y_2 = 0$",
                  "2/14",
                  "4/14",
                  "0")
JDTable[2, ] <- c("$Y_2 = 1$",
                  "0",
                  "3/14",
                  "5/14")
if (knitr::is_latex_output()) {
  kable(JDTable,
    format = "latex"   )
}
if (knitr::is_html_output()){
  kable(JDTable,
    format = "html")
}
```
:::

:::{.answer}
**Answer to Exercise \@ref(exr:GammaSum).**

$Y \sim\text{Gam}(\sum\alpha, \beta)$.
:::
  
  
:::{.answer}
**Answer to Exercise \@ref(exr:CauchySquared).**
  
Transformation is not 1-1. 
$f_Y(y)=\displaystyle {\frac{1}{\pi \sqrt{y}(1 + y)}}$ for $0 < y < \infty$.
:::

:::{.answer}
**Answer to Exercise \@ref(exr:ContTransform).**

1. $f_x(x) = x$ for $-0.5 < x < 0.5$.  
1. $F_Y(y) =\Pr(Y \le y) = 1 - 2\sqrt{4 - y}$ for $3.75 < y < 4$.
1. $f_Y(y) = (4 - y)^{-1/2}$.
:::



:::{.answer}
**Answer to Exercise \@ref(exr:BinomXform).**
See that $Y\in\{0, 1, \sqrt{2}, \\sqrt{3}, 2\}$ and so. 
\[ 
   \Pr(Y = y) = \binom{4}{y^2} (0.2)^{y^2} (0.8)^{4 - y^2} \quad \text{for $y = 0, 1, \sqrt{2}, \sqrt{3}, 2$}.
\]
:::



:::{.answer}
**Answer to Exercise \@ref(exr:GiveDF2).**
1. Differentiating:  
  \[
     f_X(x) = 
     \begin{cases}
        1, & \text{for $-0.5 < x < 0.5$}; \\
        0 & \text{elsewhere}.
     \end{cases}
  \]
  This is the uniform distribution.
2. This is not 1:1, so care needed.
   Note that $-\sqrt{4 - y} < X < \sqrt{4 - y}$.
   Then:  
   \begin{align*}
     \Pr(Y < y) = F_Y(y) =
     &= \Pr( -\sqrt{4 - y} < X < \sqrt{4 - y})\\
     &= \int_{-\sqrt{4 - y}}|^{\sqrt{4 - y}} 1\,dx = 2\sqrt{4 - y}.
   \end{align*}
   Hence. 
   \[
     f_Y(y) = \frac{d}{dy} F_Y(y) =
     \frac{-1}{4 - y}\quad\text{for $(15/4) < y < 4$}
   \]
   which must be wrong...
:::


:::{.answer}
**Answer to Exercise \@ref(exr:Projectile).**

Given that $f(\theta) = 4/\pi$ for $0 < \theta< \pi/4$, and hence $0 < D < (v^2/g)$.
Then:
\begin{align*}
  F_D(d) = \Pr(D < d) 
  &= \Pr( v^2/g\sin2\theta < d) \\
  &= \Pr(\theta < \frac{1}{2} \sin^{-1}(d g/v^2 ) \\
  &= \int_0^{\sin^{-1}(d g/v^2 )/2} \frac{4}{\pi}\, d\theta \\
  &= \frac{2}{\pi} \sin^{-1} \left( \frac{dg}{v^2} \right).
\end{align*}
So
\[
  f_D(d) = \frac{2g}{\pi v^2}\frac{1}{\sqrt{1 - d^2 g^2/v^4}}\quad\text{for $0 < D < v^2 /g$}.
\]

Suppose a projectile is fired at an angle $\theta$ from the horizontal with velocity $v$. 
The horizontal distance that the projectile travels, $D$, is

\[
   D = \frac{v^2}{g} \sin 2\theta,
\]
where $g$ is the acceleration due to gravity ($g\approx 9.8$ m.s^2^).

1. If $\theta$ is uniformly distributed over the range $(0, \pi/4)$, find the probability density function of $D$.
1. Sketch the pdf of $D$ over a suitable range for $v = 12$ and using $g\approx 9.8$$m.s^2^.
:::



