## Answers for Chap. 8

  
:::{.answer}
**Answer to Exercise \@ref(exr:CLTProb).**

$\text{E}(Y) = \int_0^1 y(3y^2)\, dy = 3/4$.
$\text{E}(Y^2) = 3/5$, so $\text{Var}(Y) = 3/80$. 
By the CLT, $\overline{Y}\sim N(3/4, 3/(80n) )$. 
Therefore

\[
   \Pr\left( 3/4 - \sqrt{3/80} < \overline{Y} < 3/4 + \sqrt{3/80} \right)
   = \Pr\left( 0.56 < \overline{Y} < 0.94 \right)
\]
is needed. For a sample of size $n$,

\[
   \Pr\left( \frac{0.56 - 0.75}{0.19/\sqrt{n}} < Z < \frac{0.56 - 0.75}{0.19/\sqrt{n}} \right)
   = \Pr(-\sqrt{n} < Z < \sqrt{n} )
\]
which approaches one as $n\to\infty$.
For example, if $n = 10$, $\Pr(-\sqrt{10} < Z < \sqrt{10} ) = 0.9984$.
:::
  

:::{.answer}
**Answer to Exercise \@ref(exr:EggsVariance).**

Let the weight be $E$, so $E\sim N(59, 0.7)$. 
By the CLT, the sample mean $\overline{E} \sim N(59, 0.7/12)$. 
So

\[
   \Pr(\overline{E} > 59.5)
   = \Pr(Z > \frac{59.5 - 59}{\sqrt{0.7/12}})
   = \Pr(z > 2.07)
   \approx 0.019.
\]
1. We seek $\Pr(s^2 > 1)$. 
   Since 
   
\[
   \frac{(n - 1)s^2}{\sigma^2}\sim \chi^2_{n - 1}
\]
where $n = 12$ and $\sigma^2 = 0.7$. 
So
\begin{align*}
   \Pr(s^2 > 1)
   &= \Pr\left( \frac{11 s^2}{0.7} > \frac{11\times 1}{0.7} \right)\\
   &=\Pr( \chi^2_{11} > 15.714)\\
   &\approx 0.152.
\end{align*}
:::
  
:::{.answer}
**Answer to Exercise \@ref(exr:EggsBroken).**

Let the number broken be $B$, so $B \sim \text{Pois}(0.2)$. 
The sample mean number broken has the distribution $\overline{B}\sim N(0.2, 0.2/\sqrt{12})$ approx. 
So

\[
   \Pr(B\ge 1) 
   = \Pr\left( Z > \frac{1 - 0.2}{\sqrt{0.2\sqrt{12}}} \right)
   = \Pr(Z > 6.196) = 0.
\]
In contrast, in any one carton, the probability of more than one
broken egg is

\[
   \Pr(B > 1) = 1 - \Pr(B = 0) = 1 - 0.8187 = 0.181
\]
using the Poisson distribution.
:::

:::{.answer}
**Answer to Exercise \@ref(exr:ContRVM).**
  
1. $\text{E}(M) = 3/4$.
1. $\text{var}(M) = 3/80$.
1. $\overline{M}\sim N(3/4, 1/240)$.
1. $0.8788$.
:::



  

  