<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>11 Multivariate distributions* | The Theory of Statistical Distributions</title>
<meta name="author" content="Peter K. Dunn and Taryn Axelsen">
<meta name="description" content="On completion of this chapter you should be able to: apply the concept of bivariate random variables. compute joint probability functions and the distribution function of two random variables....">
<meta name="generator" content="bookdown 0.45 with bs4_book()">
<meta property="og:title" content="11 Multivariate distributions* | The Theory of Statistical Distributions">
<meta property="og:type" content="book">
<meta property="og:description" content="On completion of this chapter you should be able to: apply the concept of bivariate random variables. compute joint probability functions and the distribution function of two random variables....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="11 Multivariate distributions* | The Theory of Statistical Distributions">
<meta name="twitter:description" content="On completion of this chapter you should be able to: apply the concept of bivariate random variables. compute joint probability functions and the distribution function of two random variables....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.10.0/transition.js"></script><script src="libs/bs3compat-0.10.0/tabs.js"></script><script src="libs/bs3compat-0.10.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><script src="libs/rglWebGL-binding-1.3.31/rglWebGL.js"></script><link href="libs/rglwidgetClass-1.3.31/rgl.css" rel="stylesheet">
<script src="libs/rglwidgetClass-1.3.31/rglClass.min.js"></script><script src="libs/CanvasMatrix4-1.3.31/CanvasMatrix.min.js"></script><link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="libs/plotly-binding-4.11.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><link rel="shortcut icon" href="icons/iconmonstr-chart-1-240.png">
<script>
    document.addEventListener('DOMContentLoaded', function() {
      // Find all R code blocks that should be toggleable.
      // Our Lua filter adds the 'r-code-box' class to the code block.
      var codeBlocks = document.querySelectorAll('.r-code-box');

      codeBlocks.forEach(function(codeBlock) {
        // Create the button element
        var button = document.createElement('button');
        button.textContent = 'Show R Code'; // Initial text for the button
        button.className = 'code-toggle-button'; // Assign CSS class

        // Insert the button directly before the code block.
        // The codeBlock's parentNode is the div.figure-with-code container.
        // We insert the button as a sibling of the codeBlock within that container.
        codeBlock.parentNode.insertBefore(button, codeBlock);

        // Hide the code block initially by default.
        codeBlock.style.display = 'none';

        // Add a click event listener to the button
        button.addEventListener('click', function() {
          if (codeBlock.style.display === 'none') {
            codeBlock.style.display = 'block'; // Show the code block
            button.textContent = 'Hide R Code'; // Change button text
          } else {
            codeBlock.style.display = 'none'; // Hide the code block
            button.textContent = 'Show R Code'; // Change button text back
          }
        });
      });
    });
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="bs4_style.css">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/columns.css">
<link rel="stylesheet" href="html/largerDie.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">The Theory of Statistical Distributions</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="ChapterIntroduction.html"><span class="header-section-number">1</span> Introduction</a></li>
<li class="book-part">Theoretical foundations</li>
<li><a class="" href="ChapterSetTheory.html"><span class="header-section-number">2</span> Essentials of set theory</a></li>
<li><a class="" href="ChapterProbability.html"><span class="header-section-number">3</span> Probability</a></li>
<li><a class="" href="DistributionRandomVariables.html"><span class="header-section-number">4</span> Random variables and their distributions</a></li>
<li><a class="" href="ChapBivariate.html"><span class="header-section-number">5</span> Bivariate distributions</a></li>
<li><a class="" href="ChapExpectation.html"><span class="header-section-number">6</span> Mathematical expectation</a></li>
<li class="book-part">Standard univariate probability distributions</li>
<li><a class="" href="DiscreteDistributions.html"><span class="header-section-number">7</span> Standard discrete distributions</a></li>
<li><a class="" href="ContinuousDistributions.html"><span class="header-section-number">8</span> Standard continuous distributions</a></li>
<li><a class="" href="ChapterMixedDistributions.html"><span class="header-section-number">9</span> Mixed distributions</a></li>
<li><a class="" href="ChapterTransformations.html"><span class="header-section-number">10</span> Transformations of random variables</a></li>
<li class="book-part">Multivariate random variables and distributions*</li>
<li><a class="active" href="ChapMultivariate.html"><span class="header-section-number">11</span> Multivariate distributions*</a></li>
<li><a class="" href="MultivariateExtensions.html"><span class="header-section-number">12</span> Expectations for multivariate distributions*</a></li>
<li class="book-part">Sampling distributions</li>
<li><a class="" href="SamplingDistributions.html"><span class="header-section-number">13</span> Describing samples</a></li>
<li><a class="" href="OrderStatisticsChapter.html"><span class="header-section-number">14</span> Order statistics</a></li>
<li><a class="" href="BayesianIntro.html"><span class="header-section-number">15</span> Introduction to Bayesian statistics</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="SymbolsUsed.html"><span class="header-section-number">A</span> Symbols used</a></li>
<li><a class="" href="UsefulSeries.html"><span class="header-section-number">B</span> Some useful series</a></li>
<li><a class="" href="ShortRIntro.html"><span class="header-section-number">C</span> Short R introduction</a></li>
<li><a class="" href="UseRDistributions.html"><span class="header-section-number">D</span> Using R with distributions</a></li>
<li><a class="" href="selected-short-solutions.html"><span class="header-section-number">E</span> Selected short solutions</a></li>
<li><a class="" href="references.html"><span class="header-section-number">F</span> References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/PeterKDunn/DistTheory">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="ChapMultivariate" class="section level1" number="11">
<h1>
<span class="header-section-number">11</span> Multivariate distributions*<a class="anchor" aria-label="anchor" href="#ChapMultivariate"><i class="fas fa-link"></i></a>
</h1>
<div class="objectivesBox objectives">
<p>On completion of this chapter you should be able to:</p>
<ul>
<li>apply the concept of bivariate random variables.</li>
<li>compute joint probability functions and the distribution function of two random variables.</li>
<li>find the marginal and conditional probability functions of random variables in both discrete and continuous cases.</li>
<li>apply the concept of independence of two random variables.</li>
<li>compute the expectation and variance of linear combinations of random variables.</li>
<li>interpret and compute the covariance and the coefficient of correlation between two random variables.</li>
<li>compute the conditional mean and conditional variance of a random variable for some given value of another random variable.</li>
<li>use the multinomial and bivariate normal distributions.</li>
</ul>
</div>
<div id="MultivariateIntroduction" class="section level2" number="11.1">
<h2>
<span class="header-section-number">11.1</span> Introduction<a class="anchor" aria-label="anchor" href="#MultivariateIntroduction"><i class="fas fa-link"></i></a>
</h2>
<p>Not all random processes are sufficiently simple to have the outcome denoted by a single variable <span class="math inline">\(X\)</span>.
Many situations require observing two or more numerical characteristics simultaneously.
This chapter mainly discusses the two-variable (bivariate) case, but also discusses the multivariable (more than two variables) case using matrix notation (Sect. <a href="ChapMultivariate.html#Multivariate">11.2</a>).</p>
</div>
<div id="Multivariate" class="section level2" number="11.2">
<h2>
<span class="header-section-number">11.2</span> Multivariate random variables and matrix notation<a class="anchor" aria-label="anchor" href="#Multivariate"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="RandomVectors" class="section level2" number="11.3">
<h2>
<span class="header-section-number">11.3</span> Random vectors<a class="anchor" aria-label="anchor" href="#RandomVectors"><i class="fas fa-link"></i></a>
</h2>
<p>So far, we have studied <em>univariate</em> random variables (i.e., a single random variable)
and <em>bivariate</em> random variables (two jointly distributed random variables).
These ideas can be extended to more random variables; the case of <em>multivariate</em> random variables, where several random variables are considered simultaneously.</p>
<p>To do this, using <em>random vectors</em> is convenient.
A random vector is a column vector of <span class="math inline">\(n\)</span> random variables:
<span class="math display">\[
  \mathbf{X} = [X_1, X_2, \dots, X_n]^T,
\]</span>
where the superscript <span class="math inline">\(T\)</span> means ‘transpose’.
Each <span class="math inline">\(X_i\)</span> is a random variable, and together they form an <span class="math inline">\(n\)</span>-dimensional random vector.
In the bivariate case, for example, we could write
<span class="math display">\[
   \mathbf{X}
   = \begin{bmatrix}
       X_1 \\
       X_2
     \end{bmatrix}
\]</span>
where the (column) vector <span class="math inline">\(\mathbf{a} = \begin{bmatrix} a_1 \\ a_2 \end{bmatrix}\)</span>.</p>
</div>
<div id="MultivariateProbFn" class="section level2" number="11.4">
<h2>
<span class="header-section-number">11.4</span> Joint probability functions<a class="anchor" aria-label="anchor" href="#MultivariateProbFn"><i class="fas fa-link"></i></a>
</h2>
<p>The <em>joint probability function</em> of <span class="math inline">\(\mathbf{X}\)</span> describes the probability distribution for all <span class="math inline">\(n\)</span> random variables simultaneously.</p>
<div class="definition">
<p><span id="def:JointPMF" class="definition"><strong>Definition 11.1  (Joint probability function (discrete)) </strong></span>Let <span class="math inline">\(\mathbf{X} = (X_1, \dots, X_n)\)</span> be an <span class="math inline">\(n\)</span>-dimensional discrete random variable.
The random variable <span class="math inline">\(X_j\)</span> (for <span class="math inline">\(j = 1, \dots, n\)</span>) takes values in some set <span class="math inline">\(S_j\)</span> (the range).</p>
<p>Then, the range of the random vector is
<span class="math display">\[
  \mathcal{X} \subseteq S_1\times \cdots \times S_n.
\]</span>
Then, the <em>joint probability mass function</em> is
<span class="math display">\[
  p_{X_1, \dots, X_n}(x_1, \dots, x_n)
  = \Pr(X_1 = x_1,\, \dots,\, X_n = x_n) \quad \text{for $(x_1, \dots, x_n) \in \mathcal{X}$},
\]</span>
such that
<span class="math display">\[
  p_{X_1, \dots, X_n}(x_1, \dots, x_n) \geq 0
  \quad \text{for all $(x_1, \dots, x_n) \in \mathcal{X}$},
\]</span>
and
<span class="math display">\[
  \sum_{(x_1, \dots, x_n) \in \mathcal{X}} p_{X_1, \dots, X_n}(x_1, \dots, x_n) = 1.
\]</span></p>
</div>
<div class="example">
<p><span id="exm:Dice3D" class="example"><strong>Example 11.1  (Three dice) </strong></span>Consider the random vector <span class="math inline">\(\mathbf{X} = (X_1, X_2, X_3)\)</span> representing the outcome of rolling three fair six-sided dice.</p>
<p>Since each <span class="math inline">\(X_j \in \{1,2,3,4,5,6\}\)</span>, the range is
<span class="math display">\[
  \mathcal{X} = \{1,2,3,4,5,6\} \times \{1,2,3,4,5,6\} \times \{1,2,3,4,5,6\}.
\]</span>
Assuming the dice are independent, the joint probabuility mass function is
<span class="math display">\[\begin{align*}
  p_{X_1, X_2, X_3}(x_1, x_2, x_3)
  &amp;=
  \Pr(X_1 = x_1, X_2 = x_2, X_3 = x_3)\\
  &amp;= \frac{1}{6^3} = \frac{1}{216}
\end{align*}\]</span>
for <span class="math inline">\((x_1, x_2, x_3) \in \mathcal{X}\)</span>.</p>
<p>For instance, the probability that the sum of the three dice equals <span class="math inline">\(10\)</span> is
<span class="math display">\[
  \Pr(X_1 + X_2 + X_3 = 10)
  = \sum_{\substack{(x_1, x_2, x_3) \in \mathcal{X}\\ x_1 + x_2 + x_3 = 10}} p(x_1,x_2,x_3).
\]</span></p>
<p>To obtain the answer in <strong>R</strong>, use:</p>
<div class="sourceCode" id="cb83"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># List all possible outcomes of rolling three dice</span></span>
<span><span class="va">dice_Outcomes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>x1 <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span>, </span>
<span>                             x2 <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span>, </span>
<span>                             x3 <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Show the first few rows (outcomes)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dice_Outcomes</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;   x1 x2 x3</span></span>
<span><span class="co">#&gt; 1  1  1  1</span></span>
<span><span class="co">#&gt; 2  2  1  1</span></span>
<span><span class="co">#&gt; 3  3  1  1</span></span>
<span><span class="co">#&gt; 4  4  1  1</span></span>
<span><span class="co">#&gt; 5  5  1  1</span></span>
<span><span class="co">#&gt; 6  6  1  1</span></span>
<span></span>
<span><span class="co"># Find where the rows sum to 10</span></span>
<span><span class="va">favourable_Outcome</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">dice_Outcomes</span>, </span>
<span>                             <span class="va">x1</span> <span class="op">+</span> <span class="va">x2</span> <span class="op">+</span> <span class="va">x3</span> <span class="op">==</span> <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Probability</span></span>
<span><span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">favourable_Outcome</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">dice_Outcomes</span><span class="op">)</span></span>
<span><span class="va">prob</span></span>
<span><span class="co">#&gt; [1] 0.125</span></span></code></pre></div>
</div>
<p>In the case of continuous random variables, the definition is similar.</p>
<div class="definition">
<p><span id="def:JointPDF" class="definition"><strong>Definition 11.2  (Joint probability function (continuous)) </strong></span>Let <span class="math inline">\(\mathbf{X} = (X_1, \dots, X_n)\)</span> be an <span class="math inline">\(n\)</span>-dimensional continuous random vector.
For each <span class="math inline">\(j = 1, \dots, n\)</span>, the random variable <span class="math inline">\(X_j\)</span> takes values in some subset <span class="math inline">\(S_j \subseteq \mathbb{R}\)</span>.</p>
<p>The range of the vector is therefore
<span class="math display">\[
  \mathcal{X} \subseteq S_1 \times \cdots \times S_n \subseteq \mathbb{R}^n.
\]</span>
The <em>joint probability density function</em> of <span class="math inline">\(\mathbf{X}\)</span> is
<span class="math display">\[
  f_{X_1, \dots, X_n}(x_1, \dots, x_n), \quad \text{for $(x_1, \dots, x_n) \in \mathcal{X}$},
\]</span>
such that
<span class="math display">\[
  f_{X_1, \dots, X_n}(x_1, \dots, x_n) \geq 0
  \quad \text{for all $(x_1, \dots, x_n) \in \mathcal{X}$},
\]</span>
and
<span class="math display">\[
  \int_{\mathcal{X}} f_{X_1, \dots, X_n}(x_1, \dots, x_n)\, dx_1 \cdots dx_n = 1.
\]</span></p>
</div>
<div class="example">
<p><span id="exm:UniformCube3D" class="example"><strong>Example 11.2  (Three-dimensional uniform example (continuous)) </strong></span>Consider the random vector <span class="math inline">\(\mathbf{X} = (X_1, X_2, X_3)\)</span>, uniformly distributed on the unit cube <span class="math inline">\([0, 1]^3\)</span>.<br>
The range is
<span class="math display">\[
  \mathcal{X} = [0, 1] \times [0, 1] \times [0, 1] \subset \mathbb{R}^3.
\]</span></p>
<p>The joint probability density function is:
<span class="math display">\[
  f_{X_1, X_2, X_3}(x_1,x_2,x_3) =
  \begin{cases}
    1 &amp; \text{for $0 \le x_j \le 1$ for all $j = 1, 2, 3$},\\
    0 &amp; \text{otherwise}.
  \end{cases}
\]</span></p>
<p>The marginal distributions are all uniform on <span class="math inline">\([0, 1]\)</span>; for example:
<span class="math display">\[
  f_{X_1}(x_1) = \int_0^1 \int_0^1 f(x_1, x_2, x_3)\, dx_2\, dx_3 = 1, \quad 0\le x_1 \le 1.
\]</span></p>
<p>For instance, the probability that the sum of the three variables is less than or equal to <span class="math inline">\(1\)</span> is
<span class="math display">\[
  \Pr(X_1 + X_2 + X_3 \le 1)
  = \text{volume of the tetrahedron } \{(x_1,x_2,x_3)\in\mathcal{X}: x_1 + x_2 + x_3 \le 1\}
  = \frac{1}{6}.
\]</span></p>
<p>The answer can be obtained using integration, knowledge of volumes, or using a simulation in <strong>R</strong>:</p>
<div class="sourceCode" id="cb84"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">30991</span><span class="op">)</span> <span class="co"># For reproducibility</span></span>
<span></span>
<span><span class="co"># Generate 1 000 000 random points in each dimension of the cube</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">1e6</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">3</span> <span class="op">*</span> <span class="va">N</span><span class="op">)</span>, </span>
<span>            ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>  <span class="co"># N rows of (x1,x2,x3)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;            [,1]        [,2]      [,3]</span></span>
<span><span class="co">#&gt; [1,] 0.01910142 0.876909934 0.1347004</span></span>
<span><span class="co">#&gt; [2,] 0.41801207 0.146094920 0.5405445</span></span>
<span><span class="co">#&gt; [3,] 0.86790140 0.008614253 0.6262534</span></span>
<span><span class="co">#&gt; [4,] 0.20781771 0.648519075 0.2852823</span></span>
<span><span class="co">#&gt; [5,] 0.07213365 0.119805842 0.6374308</span></span>
<span><span class="co">#&gt; [6,] 0.70971854 0.642130898 0.1407279</span></span>
<span></span>
<span><span class="co"># How many of these random points satisfy: sum less than one?</span></span>
<span><span class="va">prob_Est</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">&lt;=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">prob_Est</span></span>
<span><span class="co">#&gt; [1] 0.166457</span></span></code></pre></div>
</div>
</div>
<div id="MultivariateDistFn" class="section level2" number="11.5">
<h2>
<span class="header-section-number">11.5</span> Joint distribution functions<a class="anchor" aria-label="anchor" href="#MultivariateDistFn"><i class="fas fa-link"></i></a>
</h2>
<p>The <em>multivariate distribution function (CDF)</em> is
<span class="math display">\[
  F_{X_1, \dots, X_n}(x_1, \dots, x_n)
  = \Pr(X_1 \leq x_1, \dots, X_n \leq x_n).
\]</span></p>
<div class="example">
<p><span id="exm:Dice3D_CDF" class="example"><strong>(#exm:Dice3D_CDF) (Three dice) </strong></span>Let <span class="math inline">\(\mathbf{X} = (X_1, X_2, X_3)\)</span> be the random vector representing the outcome of rolling three fair six-sided dice, as in Example <a href="ChapMultivariate.html#exm:Dice3D">11.1</a> (where the joint probability mass function is given).</p>
<p>The <em>joint cumulative distribution function</em> is
<span class="math display">\[
  F_{X_1, X_2, X_3}(x_1, x_2, x_3)
  = \Pr(X_1 \le x_1, X_2 \le x_2, X_3 \le x_3)
  = \sum_{i = 1}^{\lfloor x_1 \rfloor}
    \sum_{j = 1}^{\lfloor x_2 \rfloor} \sum_{k = 1}^{\lfloor x_3 \rfloor} p(i, j, k),
\]</span>
where <span class="math inline">\(\lfloor x \rfloor\)</span> is the <em>floor</em> function (the greatest integer less than or equal to <span class="math inline">\(x\)</span>).</p>
<p>For instance, the probability that all dice shows less than or equal to <span class="math inline">\(3\)</span> is
<span class="math display">\[
  F_{X_1, \dots, X_n}(3, 3, 3)
  = \sum_{i = 1}^{3} \sum_{j = 1}^{3} \sum_{k = 1}^{3} \frac{1}{216}
  = \frac{27}{216} = \frac{1}{8}.
\]</span></p>
</div>
<div class="example">
<p><span id="exm:UniformCube3D_CDF" class="example"><strong>(#exm:UniformCube3D_CDF) (Three-Dimensional Uniform Cube: CDF) </strong></span>Let <span class="math inline">\(\mathbf{X} = (X_1, X_2, X_3)\)</span> be uniformly distributed on the unit cube <span class="math inline">\([0, 1]^3\)</span>, as in Example <a href="ChapMultivariate.html#exm:UniformCube3D">11.2</a> (where the joint probability density function is given)</p>
<p>The <em>joint cumulative distribution function</em> is
<span class="math display">\[\begin{align*}
  F_{X_1, \dots, X_n}(x_1, x_2, x_3)
  &amp;= \Pr(X_1 \le x_1, X_2 \le x_2, X_3 \le x_3)\\
  &amp;= \int_0^{x_1}\!\! \int_0^{x_2}\!\! \int_0^{x_3} f(u_1, u_2, u_3)\, du_3\, du_2\, du_1,
\end{align*}\]</span>
for <span class="math inline">\(0 \le x_1, x_2, x_3 \le 1\)</span>.</p>
<p>For instance, the probability that each variable is less than <span class="math inline">\(0.5\)</span> is
<span class="math display">\[
  Fvs(0.5, 0.5, 0.5) = \int_0^{0.5}\!\! \int_0^{0.5}\!\! \int_0^{0.5} 1 \, du_3\, du_2\, du_1 = 0.5^3 = 0.125.
\]</span></p>
</div>
</div>
<div id="marginal-and-conditional-distributions" class="section level2" number="11.6">
<h2>
<span class="header-section-number">11.6</span> Marginal and conditional distributions<a class="anchor" aria-label="anchor" href="#marginal-and-conditional-distributions"><i class="fas fa-link"></i></a>
</h2>
<p>Marginal distributions are obtained by summing or integrating out unwanted variables. For example,
<span class="math display">\[
  f_{X_1}(x_1) = \int_{\mathbb{R}^{n-1}} f(x_1, x_2, \dots, x_n)\, dx_2 \cdots dx_n.
\]</span></p>
<p>Conditional distributions are defined in the natural way:
<span class="math display">\[
  f_{X_1 \mid X_2, \dots, X_n}(x_1 \mid x_2, \dots, x_n) =
  \frac{f(x_1, x_2, \dots, x_n)}{f_{X_2,\dots,X_n}(x_2, \dots, x_n)}.
\]</span></p>
<p>EXAMPLES</p>
</div>
<div id="MultivariateIndependence" class="section level2" number="11.7">
<h2>
<span class="header-section-number">11.7</span> Multivariate independence<a class="anchor" aria-label="anchor" href="#MultivariateIndependence"><i class="fas fa-link"></i></a>
</h2>
<p>In the multivariate case, <span class="math inline">\(n\)</span> random variables <span class="math inline">\(X_1, \dots, X_n\)</span> are <em>independent</em> if knowing the value of any subset of them gives no information about the others.
Formally, let <span class="math inline">\(\mathbf{X} = (X_1, \dots, X_n)\)</span> be an <span class="math inline">\(n\)</span>-dimensional random vector with joint probability distribution.</p>
<p>In the <em>discrete case</em>, the random variables are independent if and only if the joint probability mass function factors as the product of the marginal probability functions:
<span class="math display">\[
  p_{X_1, \dots, X_n}(x_1, \dots, x_n)
  = \prod_{i = 1}^{n} p_{X_i}(x_i),
  \quad (x_1, \dots, x_n) \in \mathcal{X}.
\]</span></p>
<p>The <em>continuous case</em> is similar; the random variables are independent if and only if the joint probability density function factors as the product of the marginal densities:
<span class="math display">\[
  f_{X_1, \dots, X_n}(x_1, \dots, x_n)
  = \prod_{i = 1}^{n} f_{X_i}(x_i),
  \quad (x_1, \dots, x_n) \in \mathcal{X}.
\]</span></p>
<p>Independence can also be determined using the distribution functions:
<span class="math display">\[
  F_{X_1, \dots, X_n}(x_1, \dots, x_n) = \prod_{i=1}^{n} F_{X_i}(x_i),
\]</span>
where <span class="math inline">\(F\)</span> is the joint cumulative distribution function.</p>
<p>In practice, independence allows joint probabilities or volumes to be computed by multiplying the corresponding marginal probabilities or integrating products of marginal densities.</p>
<div class="example">
<p><span id="exm:Dice3D_Indep" class="example"><strong>(#exm:Dice3D_Indep) (Three dice example: independence) </strong></span>Consider the outcomes of rolling three fair six-sided dice, represented by the random vector <span class="math inline">\(\mathbf{X} = (X_1, X_2, X_3)\)</span>.<br>
Each <span class="math inline">\(X_j \in \{1,2,3,4,5,6\}\)</span>, so <span class="math inline">\(\mathcal{X} = \{1,\dots,6\}^3\)</span>.
The dice are independent, so the joint probability mass function can be written as the product of the marginal probability functions:
<span class="math display">\[
  p_{X_1, X_2, X_3}(x_1, x_2, x_3)
  = \Pr(X_1 = x_1, X_2 = x_2, X_3 = x_3)
  = \prod_{i = 1}^3 \Pr(X_i = x_i)
  = \frac{1}{6}\cdot   \frac{1}{6} \cdot \frac{1}{6} = \frac{1}{216}.
\]</span>
Equivalently, the joint distribution factors as
<span class="math display">\[
  F_{X_1, X_2, X_3}(x_1, x_2, x_3) = \Pr(X_1\le x_1, X_2 \le x_2, X_3 \le x_3)
  = \prod_{i = 1}^3 F_{X_i}(x_i).
\]</span>
The probability that all dice show a value less than or equal to <span class="math inline">\(3\)</span> is
<span class="math display">\[
  F_{X_1, \dots, X_n}(3, 3, 3)
  = \prod_{i = 1}^3 F_{X_i}(3)
  = \left(\frac{3}{6}\right)^3
  = \frac{27}{216} = \frac{1}{8}.
\]</span></p>
</div>
<div class="example">
<p><span id="exm:UniformCube3D_Indep" class="example"><strong>(#exm:UniformCube3D_Indep) (Three-dimensional uniform cube: independence) </strong></span>Let <span class="math inline">\(\mathbf{X} = (X_1, X_2, X_3)\)</span> be uniformly distributed on the unit cube <span class="math inline">\([0, 1]^3\)</span>, with joint probability density function
<span class="math display">\[
  f_{X_1, X_2, X_3}(x_1, x_2, x_3) = 1, \quad (x_1, x_2, x_3) \in [0, 1]^3.
\]</span></p>
<p>The variables <span class="math inline">\(X_1, X_2, X_3\)</span> are independent, so the joint density function can be written as
<span class="math display">\[
  f(x_1, x_2, x_3)
  = f_{X_1}(x_1)\cdot f_{X_2}(x_2)\cdot f_{X_3}(x_3)
  = 1 \cdot 1 \cdot 1.
\]</span></p>
<p>Equivalently, the joint distribution can be written as
<span class="math display">\[
  F_{X_1, X_2, X_3}(x_1, x_2, x_3)
  = \Pr(X_1 \le x_1, X_2 \le x_2, X_3 \le x_3)
  = \prod_{i = 1}^3 F_{X_i}(x_i).
\]</span></p>
<p>For example, the probability that the values of all three variables are less than <span class="math inline">\(0.5\)</span> is
<span class="math display">\[
  F_{X_1, X_2, X_3}(0.5, 0.5, 0.5) = 0.5^3 = 0.125.
\]</span></p>
</div>
</div>
<div id="BVNormalDistribution" class="section level2" number="11.8">
<h2>
<span class="header-section-number">11.8</span> The bivariate normal distribution<a class="anchor" aria-label="anchor" href="#BVNormalDistribution"><i class="fas fa-link"></i></a>
</h2>
<p>
A specific example of a <em>continuous</em> multivariate distribution is the <em>bivariate normal distribution</em>.</p>
<div class="definition">
<p><span id="def:BVNormalDistribution" class="definition"><strong>Definition 11.3  (The bivariate normal distribution) </strong></span>If a pair of random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> have the joint PDF
<span class="math display" id="eq:bivarnormalPDF">\[\begin{equation}
   f_{X, Y}(x, y; \mu_x, \mu_Y, \sigma^2_X, \sigma^2_Y, \rho) =
   \frac{1}{2\pi\sigma_X\sigma_Y\sqrt{1 - \rho^2}}\exp(-Q/2)
   \tag{11.1}
\end{equation}\]</span>
where
<span class="math display">\[
   Q = \frac{1}{1-\rho^2}\left[
                      \left(\frac{x-\mu_X}{\sigma_X}\right)^2 -
                2\rho\left( \frac{x-\mu_X}{\sigma_X}\right)\left(\frac{y-\mu_Y}{\sigma_Y}\right)
                +     \left(\frac{y-\mu_Y}{\sigma_Y}\right)^2 \right],
\]</span>
then <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> have a <em>bivariate normal distribution</em>.
We write
<span class="math display">\[
   (X, Y) \sim N_2(\mu_X, \mu_Y, \sigma^2_X, \sigma^2_Y, \rho ).
\]</span></p>
</div>
<p>A typical graph of the bivariate normal surface above the <span class="math inline">\(x\)</span>–<span class="math inline">\(y\)</span> plane is shown
below.
Showing <span class="math inline">\(\int^\infty_{-\infty}\!\int^\infty_{-\infty}f_{X,Y}(x,y)\,dx\,dy = 1\)</span> is not straightforward and involves writing Eq. <a href="ChapMultivariate.html#eq:bivarnormalPDF">(11.1)</a> using polar coordinates.</p>
<p>Some important facts about the bivariate normal distribution are contained in the theorem below.</p>
<div class="theorem">
<p><span id="thm:BivarNormalProperties" class="theorem"><strong>Theorem 11.1  (Bivariate normal distribution properties) </strong></span>For <span class="math inline">\((X, Y)\)</span> with PDF given in Eq. <a href="ChapMultivariate.html#eq:bivarnormalPDF">(11.1)</a>:</p>
<ol style="list-style-type: decimal">
<li>The marginal distributions of <span class="math inline">\(X\)</span> and of <span class="math inline">\(Y\)</span> are <span class="math inline">\(N(\mu_X, \sigma^2_X)\)</span> and <span class="math inline">\(N(\mu_Y, \sigma^2_Y)\)</span> respectively.</li>
<li>The parameter <span class="math inline">\(\rho\)</span> appearing in Eq. <a href="ChapMultivariate.html#eq:bivarnormalPDF">(11.1)</a> is the correlation coefficient between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>the conditional distributions of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y = y\)</span>, and of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X = x\)</span>, are respectively
<span class="math display">\[\begin{align*}
  &amp;N\left( \mu_X + \rho \sigma_X(y - \mu_Y)/\sigma_Y, \sigma^2_X(1 - \rho^2)\right); \\
  &amp;N\left( \mu_Y + \rho \sigma_Y(x - \mu_X)/\sigma_X, \sigma^2_Y(1 - \rho^2)\right).
  \end{align*}\]</span>
</li>
</ol>
<div class="proof">
<p><span id="unlabeled-div-63" class="proof"><em>Proof</em>. </span>Recall that the marginal PDF of <span class="math inline">\(X\)</span> is <span class="math inline">\(f_X(x) = \int^\infty_{-\infty} f_{X, Y}(x, y)\,dy\)</span>.
In the integral, put <span class="math inline">\(u = (x - \mu_X)/\sigma_X, v = (y - \mu_Y)/\sigma_Y,\, dy = \sigma_Y\,dv\)</span> and complete the square in the exponent on <span class="math inline">\(v\)</span>:
<span class="math display">\[\begin{align*}
     g(x)
     &amp;= \frac{1}{2\pi\sigma_X\sqrt{1 - \rho^2}\sigma_Y}\int^\infty_{-\infty}\exp\left\{ -\frac{1}{2(1 - \rho^2)}\left[ u^2 - 2\rho uv + v^2\right]\right\} \sigma_Y\,dv\\[2mm]
     &amp;= \frac{1}{2\pi \sigma_X\sqrt{1 - \rho^2}}\int^\infty_{-\infty} \exp\left\{ -\frac{1}{2(1 - \rho^2)}\left[ (v - \rho u)^2 + u^2 - \rho^2u^2\right]\right\}\,dv\\[2mm]
     &amp;= \frac{e^{-u^2/2}}{\sqrt{2\pi} \sigma_X} \ \underbrace{\int^\infty_{-\infty} \frac{1}{\sqrt{2\pi (1 - \rho^2)}} \exp\left\{ -\frac{1}{2(1 - \rho^2)}(v - \rho u)^2\right\}\,dv}_{=1}.
\end{align*}\]</span>
Replacing <span class="math inline">\(u\)</span> by <span class="math inline">\((x - \mu_X )/\sigma_X\)</span>, we see from the PDF that <span class="math inline">\(X \sim N(\mu_X, \sigma^2_X)\)</span>.
Similarly for the marginal PDF of <span class="math inline">\(Y\)</span>; i.e., <span class="math inline">\(f_Y(y)\)</span>.</p>
<p>To show that <span class="math inline">\(\rho\)</span> in Eq. <a href="ChapMultivariate.html#eq:bivarnormalPDF">(11.1)</a> is the correlation coefficient of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, recall that
<span class="math display">\[\begin{align*}
     \rho_{X,Y}
     &amp;= \operatorname{Cov}(X,Y)/\sigma_X\sigma_Y=\operatorname{E}[(X-\mu_X)(Y - \mu_Y)]/\sigma_X\sigma_Y   \\[2mm]
     &amp; = \int^\infty_{-\infty}\!\int^\infty_{-\infty} \frac{(x - \mu_X)}{\sigma_X}\frac{(y - \mu_Y)}{\sigma_Y}f(x,y)\,dx\,dy\\[2mm]
     &amp;= \int^\infty_{-\infty}\!\int^\infty_{-\infty} uv\frac{1}{2\pi\sqrt{1 - \rho^2} \sigma_X\sigma_Y}\exp\left\{ -\frac {1}{2(1 - \rho^2)}[u^2 - 2\rho uv + v^2]\right\} \sigma_X\sigma_Y\,du\,dv.
\end{align*}\]</span></p>
<p>The exponent is
<span class="math display">\[
   -\frac{[(u - \rho v)^2 + v^2 - \rho^2 v^2]}{2(1 - \rho^2)}
   = - \frac{1}{2} \left\{\frac{(u - \rho v)^2}{(1 - \rho^2)} + v^2\right\}.
\]</span>
Then:
<span class="math display">\[\begin{align*}
   \rho_{X, Y}
   &amp;=\int^\infty_{-\infty}\frac{v e^{-v^2/2}}{\sqrt{2\pi}}\underbrace{\int^\infty_{-\infty} \frac{u}{\sqrt{2\pi
  (1 - \rho^2)}}\exp\{ -(u - \rho v)^2/2(1 - \rho^2)\}\,du}_{\displaystyle{= \operatorname{E}[U]\text{ where } u \sim N(\rho
  v, 1 - \rho^2) = \rho v}}\,dv \\[2mm]
   &amp;= \rho \int^\infty_{-\infty} \frac{v^2}{\sqrt{2\pi}}e^{-v^2/2}\,dv\\[2mm]
   &amp;= \rho\quad \text{since the integral is $\operatorname{E}[V^2]$ where $V \sim N(0,1)$.}
\end{align*}\]</span></p>
<p>In finding the conditional PDF of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y = y\)</span>, use
<span class="math display">\[
   f_{X \mid Y = y}(x) = f_{X, Y}(x, y)/f_Y(y).
\]</span>
Then in this ratio, the constant is
<span class="math display">\[
  \frac{\sqrt{2\pi} \sigma_Y}{2\pi \sigma_X\sigma_Y \sqrt{1 - \rho^2}}
  = \frac{1}{\sqrt{2\pi}\sigma_X\sqrt{1 - \rho^2}}.
\]</span>
The exponent is
<span class="math display">\[\begin{align*}
       &amp; \frac{\exp\left\{ -\left[ \displaystyle{\frac{(x - \mu_X)^2}{\sigma^2_X}} -
  \displaystyle{\frac{2\rho(x - \mu_X)(y - \mu_Y)}{\sigma_X\sigma_Y}} +
  \displaystyle{\frac{(y - \mu_Y)^2}{\sigma^2_Y}}\right] / 2(1 - \rho^2) \right\}  }{\exp\left[ -(y - \mu_Y)^2 / 2\sigma^2_Y\right]}\\[2mm]
       &amp;= \exp\left\{ - \frac{1}{2(1 - \rho^2)} \left[ \frac{(x - \mu_X)^2}{\sigma^2_X} - \frac{2\rho (x - \mu_X)(y - \mu_Y)}{\sigma_X\sigma_Y} +
  \frac{(y - \mu_Y)^2}{\sigma^2_Y} (1 - 1 + \rho^2)\right] \right\}\\[2mm]
       &amp;= \exp\left\{ - \frac{1}{2\sigma^2_X(1 - \rho^2)}
       \left[ (x - \mu_X)^2 - 2\rho \frac{\sigma_X}{\sigma_Y} (x - \mu_X)(y - \mu_Y) +
       \frac{\rho^2 \sigma^2_X}{\sigma^2_Y}(y - \mu_Y)^2\right]\right\}\\[2mm]
       &amp;= \exp \left\{ - \frac{1}{2(1 - \rho^2)\sigma^2_X} \left[ x - \mu_X - \rho\frac{\sigma_X}{\sigma_Y}(y - \mu_Y)\right]^2\right\}.
\end{align*}\]</span>
So the conditional distribution of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y = y\)</span> is
<span class="math display">\[
   N\left( \mu_X + \rho\frac{\sigma_X}{\sigma_Y}(y - \mu_Y), \sigma^2_X(1 - \rho^2)\right).
\]</span>
Recall the interpretation of the conditional distribution of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y = y\)</span> (Sect. <a href="ChapBivariate.html#ConditionalDistributions">5.5</a>) and note the shape of this density
below.</p>
</div>
</div>
<p>Comments about Theorem <a href="ChapMultivariate.html#thm:BivarNormalProperties">11.1</a>:</p>
<ul>
<li>From the first and third parts, <span class="math inline">\(\operatorname{E}[X] = \mu_X\)</span> and <span class="math inline">\(\operatorname{E}[X \mid Y = y] = \mu_X + \rho \sigma_X (y - \mu_Y)/\sigma_Y\)</span> (and similarly for <span class="math inline">\(Y\)</span>).
Notice that <span class="math inline">\(\operatorname{E}[X \mid Y = y]\)</span> is a linear function of <span class="math inline">\(y\)</span>; i.e., if <span class="math inline">\((X, Y)\)</span> is bivariate normal, the regression line of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> (and <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span>) is linear.</li>
<li>An important result follows from the second part.
If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are uncorrelated (i.e., if <span class="math inline">\(\rho = 0\)</span>) then <span class="math inline">\(f_{X, Y}(x, y) = f_X(x) f_Y(y)\)</span> and thus <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent.
That is, if two normally distributed random variables are uncorrelated, they are also independent.</li>
</ul>
<div class="example">
<p><span id="exm:BivariateHeights" class="example"><strong>Example 11.3  (Bivariate normal: Heights) </strong></span><span class="citation">(<a href="references.html#ref-data:Marsh1988:ExploringData">Badiou, Marsh, and Gauchet 1988</a>)</span> gives data from <span class="math inline">\(200\)</span> married men and their wives from the OPCS study of heights and weights of adults in Great Britain in 1980.
Histograms of the husbands’ and wives’ heights are given in Fig. <a href="ChapMultivariate.html#fig:HtsPlots">11.1</a> (left and centre panels); the marginal distributions are approximately normal.
The scatterplot of the heights is shown in Fig. <a href="ChapMultivariate.html#fig:HtsPlots">11.1</a> (right panel).</p>
<p>From the histograms, there is reason to suspect that a bivariate normal distribution would be appropriate.
Using <span class="math inline">\(H\)</span> to refer to heights (in mm) of husbands and <span class="math inline">\(W\)</span> to the heights (in mm) of wives, the sample statistics are shown below (and where the estimate of the correlation is <span class="math inline">\(+0.364\)</span>):</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>Statistic</th>
<th>Husbands</th>
<th>Wives</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Sample mean (in mm):</td>
<td>1732</td>
<td>1602</td>
</tr>
<tr class="even">
<td>Sample std dev (in mm):</td>
<td>68.8</td>
<td>62.4</td>
</tr>
</tbody>
</table></div>
<p>Note that <span class="math inline">\(\rho\)</span> is positive; this implies taller men marry taller women on average.
Using this sample information, the bivariate normal distribution can be estimated.
This <span class="math inline">\(3\)</span>-dimensional density function can be difficult to plot on a two-dimensional page, but see
below.</p>
<p>The PDF for the bivariate normal distribution for the heights of the husbands and wives could be written down in the form of <a href="ChapMultivariate.html#eq:bivarnormalPDF">(11.1)</a> for the values of <span class="math inline">\(\mu_H\)</span>, <span class="math inline">\(\mu_W\)</span>, <span class="math inline">\(\sigma^2_H\)</span>, <span class="math inline">\(\sigma^2_W\)</span> and <span class="math inline">\(\rho\)</span> above, but this is tedious.</p>
<p>Given the information, what is the probability that a randomly chosen man in the UK in 1980 who is <span class="math inline">\(173\,\text{cm}\)</span> tall had married a woman taller than himself?</p>
<p>The information implies that <span class="math inline">\(H = 1730\)</span> is given (remembering the data are given in millimetres).
So we need the <em>conditional distribution</em> of <span class="math inline">\(W \mid H = 1730\)</span>.
Using the results above, this conditional distribution will have mean
<span class="math display">\[\begin{align*}
   b
   &amp;= \mu_W + \rho\frac{\sigma_W}{\sigma_H}(y_H - \mu_H) \\
   &amp;= 1602 + 0.364\frac{62.4}{68.8}(1730 - 1732) \\
   &amp;= 1601.34
\end{align*}\]</span>
and variance
<span class="math display">\[
   \sigma_2^2(1 - \rho^2) = 62.4^2(1 - 0.364^2) = 377.85.
\]</span>
In summary, <span class="math inline">\(W \mid  (H = 1730) \sim N(1601.34, 3377.85)\)</span>.
Note that this conditional distribution has a univariate normal distribution, and so probabilities such as <span class="math inline">\(W &gt; 1730\)</span> are easily determined.
Then,
<span class="math display">\[\begin{align*}
   \Pr(W &gt; 1730 \mid H = 1730)
   &amp;= \Pr\left( Z &gt; \frac{1730 - 1601.34}{\sqrt{3377.85}}\right) \\
   &amp;= \Pr( Z &gt; 2.2137)\\
   &amp;= 0.013.
\end{align*}\]</span>
Approximately <span class="math inline">\(1.3\)</span>% of males <span class="math inline">\(173\,\text{cm}\)</span> tall had married women taller than themselves in the UK in 1980.</p>
</div>
<div class="figure">
<span style="display:block;" id="fig:HtsPlots"></span>
<img src="11-Multivariate_files/figure-html/HtsPlots-1.png" alt="Plots of the heights data." width="100%"><p class="caption">
FIGURE 11.1: Plots of the heights data.
</p>
</div>
<pre><code>#&gt; INSIDE</code></pre>
<p></p>
</div>
<div id="MultinomialDistribution" class="section level2" number="11.9">
<h2>
<span class="header-section-number">11.9</span> Multinomial distribution<a class="anchor" aria-label="anchor" href="#MultinomialDistribution"><i class="fas fa-link"></i></a>
</h2>
<p>
A specific example of a <em>discrete</em> multivariate distribution is the <em>multinomial distribution</em>, a generalization of the binomial distribution.</p>
<div class="definition">
<p><span id="def:MultinomialDistribution" class="definition"><strong>Definition 11.4  (Multinomial distribution) </strong></span>Consider an experiment with the the sample space partitioned as <span class="math inline">\(S = \{B_1, B_2, \ldots, B_k\}\)</span>.
Let <span class="math inline">\(p_i = \Pr(B_i), \ i = 1, 2,\ldots k\)</span> where <span class="math inline">\(\sum_{i = 1}^k p_i = 1\)</span>.
Suppose there are <span class="math inline">\(n\)</span> repetitions of the experiment in which <span class="math inline">\(p_i\)</span> is constant.
Let the random variable <span class="math inline">\(X_i\)</span> be the number of times (in the <span class="math inline">\(n\)</span> repetitions) that the event <span class="math inline">\(B_i\)</span> occurs.
In this situation, the random vector <span class="math inline">\((X_1, X_2, \dots, X_k)\)</span> is said to have a <em>multinomial distribution</em> with probability function
<span class="math display" id="eq:Multinomial">\[\begin{equation}
   \Pr(X_1 = x_1, X_2 = x_2, \ldots, X_k = x_k)
   = \frac{n!}{x_1! \, x_2! \ldots x_k!}
      p_1^{x_1}\, p_2^{x_2} \ldots p_k^{x_k},
   \tag{11.2}
\end{equation}\]</span>
where <span class="math inline">\(\mathcal{R}_X = \{(x_1, \ldots x_k) : x_i = 0,1,\ldots,n, \, i = 1, 2, \ldots k, \, \sum_{i = 1}^k x_i = n\}\)</span>.</p>
</div>
<p>The part of Eq. <a href="ChapMultivariate.html#eq:Multinomial">(11.2)</a> involving factorials arises as the number of ways of arranging <span class="math inline">\(n\)</span> objects, <span class="math inline">\(x_1\)</span> of which are of the first kind, <span class="math inline">\(x_2\)</span> of which are of the second kind, etc.
The above distribution is <span class="math inline">\((k - 1)\)</span>-variate since <span class="math inline">\(x_k = n-\sum_{i = 1}^{k - 1}x_i\)</span>.
In particular if <span class="math inline">\(k = 2\)</span>, the multinomial distribution reduces to the binomial distribution which is a univariate distribution.</p>
<p><span class="math inline">\(X_i\)</span> is the number of times (out of <span class="math inline">\(n\)</span>) that the event <span class="math inline">\(B_i\)</span>, which has probability <span class="math inline">\(p_i\)</span>, occurs.
So the random variable <span class="math inline">\(X_i\)</span> clearly has a binomial distribution with parameters <span class="math inline">\(n\)</span> and <span class="math inline">\(p_i\)</span>.
We see then that the marginal probability distribution of one of the components of a multinomial distribution is a binomial distribution.</p>
<p>Notice that the distribution in Example <a href="ChapBivariate.html#exm:BVDiscreteTwoDice">5.6</a> is an example of a <em>trinomial distribution</em>.
The probabilities shown in Table <a href="ChapBivariate.html#tab:BVTwoDice">5.3</a> can be expressed algebraically as
<span class="math display">\[
   \Pr(X = x, Y = y)
   = \frac{2!}{x! \, y!(2 - x - y)!}
      \left(\frac{1}{6}\right)^x\left(\frac{1}{6}\right)^y\left(\frac{2}{3}\right)^ {2 - x - y}
\]</span>
for <span class="math inline">\(x, y = 0 , 1 , 2\)</span>; <span class="math inline">\(x + y \leq 2\)</span>.</p>
<p>The following are the basic properties of the multinomial distribution.</p>
<div class="theorem">
<p><span id="thm:MultinomialProperties" class="theorem"><strong>Theorem 11.2  (Multinomial distribution properties) </strong></span>Suppose <span class="math inline">\((X_1, X_2, \ldots, X_k)\)</span> has the multinomial distribution given in Def. <a href="ChapMultivariate.html#def:MultinomialDistribution">11.4</a>.
Then for <span class="math inline">\(i = 1, 2, \ldots, k\)</span>:</p>
<ul>
<li>
<span class="math inline">\(\operatorname{E}[X_i] = np_i\)</span>.</li>
<li>
<span class="math inline">\(\operatorname{var}[X_i] = n p_i(1 - p_i)\)</span>.</li>
<li>
<span class="math inline">\(\operatorname{Cov}(X_i, X_j) = -n p_i p_j\)</span> for <span class="math inline">\(i \neq j\)</span>.</li>
</ul>
<div class="proof">
<p><span id="unlabeled-div-64" class="proof"><em>Proof</em>. </span>The first two results follow from the fact that <span class="math inline">\(X_i \sim \text{Bin}(n, p_i)\)</span>.</p>
<p>We will use <span class="math inline">\(x\)</span> for <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span> for <span class="math inline">\(x_2\)</span> in the third for convenience.
Consider only the case <span class="math inline">\(k = 3\)</span>, and note that
<span class="math display">\[
   \sum_{(x, y) \in R}
   \frac{n!}{x! \, y! (n - x - y)!} p_1^x p_2^y (1 - p_1 - p_2)^{n - x - y} = 1.
\]</span>
Then, putting <span class="math inline">\(p_3 = 1 - p_1 - p_2\)</span>,
<span class="math display">\[\begin{align*}
  E(XY)
  &amp;= \sum_{(x, y)}xy \Pr(X = x, Y = y)\\
  &amp;= \sum_{(x, y)}\frac{n!}{(x - 1)!(y - 1)!(n - x - y)!} p_1^x  p_2^y p_3^{n - x - y}\\
  &amp;= n(n - 1) p_1 p_2\underbrace{\sum_{(x,y)}\frac{(n - 2)!}{(x - 1)!(y - 1)!(n - x - y)!} p_1^{x - 1} p_2^{y - 1}p_3^{n - x - y}}_{ = 1}.
\end{align*}\]</span>
So <span class="math inline">\(\operatorname{Cov}(X, Y) = n^2 p_1 p_2 - n p_1 p_2 - (n p_1)(n p_2) = -n p_1 p_2\)</span>.</p>
</div>
</div>
<div class="softwareBox software">
<p>The two <strong>R</strong> functions for working with the multinomial distribution functions have the form <code>[dr]multinom(size, prob)</code> where <code>size</code><span class="math inline">\({}= n\)</span> and <code>prob</code><span class="math inline">\({} = (p_1, p_2, \dots, p_k)\)</span> for <span class="math inline">\(k\)</span> categories (see App. <a href="UseRDistributions.html#UseRDistributions">D</a>).
Note that the functions <code>qmultinom()</code> and <code>pmultinom()</code> are not defined.</p>
</div>
<div class="example">
<p><span id="exm:Multinomial" class="example"><strong>Example 11.4  (Multinomial distribution) </strong></span>Suppose that the four basic blood groups O, A, B and AB are known to occur in the proportions <span class="math inline">\(9:8:2:1\)</span>.
Given a random sample of <span class="math inline">\(8\)</span> individuals, what is the probability that there will be <span class="math inline">\(3\)</span> each of Types O and A and <span class="math inline">\(1\)</span> each of Types B and AB?</p>
<p>The probabilities are <span class="math inline">\(p_1 = 0.45\)</span>, <span class="math inline">\(p_2 = 0.4\)</span>, <span class="math inline">\(p_3 = 0.1\)</span>, <span class="math inline">\(p_4 = 0.05\)</span>, and
<span class="math display">\[\begin{align*}
   \Pr(X_O = 3, X_A = 3, X_B = 1, X_{AB} = 1)
   &amp;= \frac{8!}{3!\,3!\,1!\,1!}(0.45)^3 (0.4)^3 (0.1)(.05)\\
   &amp;= 0.033.
\end{align*}\]</span>
In <strong>R</strong>:</p>
<div class="sourceCode" id="cb86"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Multinom.html">dmultinom</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>, </span>
<span>          size <span class="op">=</span> <span class="fl">8</span>, </span>
<span>          prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.45</span>, <span class="fl">0.4</span>, <span class="fl">0.1</span>, <span class="fl">0.05</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.0326592</span></span></code></pre></div>
</div>
<p></p>
</div>
<div id="MultivariateExercises" class="section level2" number="11.10">
<h2>
<span class="header-section-number">11.10</span> Exercises<a class="anchor" aria-label="anchor" href="#MultivariateExercises"><i class="fas fa-link"></i></a>
</h2>
<p>Selected answers appear in Sect. <a href="selected-short-solutions.html#AnswersChapMultivariate">E.10</a>.</p>
<div class="exercise">
<p><span id="exr:MultivariateNormal" class="exercise"><strong>Exercise 11.1  </strong></span>Let <span class="math inline">\(X_1, X_2\)</span> be i.i.d. <span class="math inline">\(N(0,1)\)</span>.
Consider the polar coordinates as a bivariate transformation:
<span class="math display">\[
  X_1 = R \cos(\Theta) \quad \text{and} \quad X_2 = R \sin(\Theta).
\]</span>
1. Calculate the Jacobian of the transformation.
2. Find the joint PDF in terms of <span class="math inline">\(r\)</span> and <span class="math inline">\(\theta\)</span>.
3. Show that the resulting PDF can be factored into a function of <span class="math inline">\(r\)</span> and a function of <span class="math inline">\(\theta\)</span>.
What does that tell us about the independence of the radius and the angle?
3. Hence show that the bivariate normal distribution is a valid joint PDF.</p>
</div>

</div>
</div>
<hr>
<div class="footer"><span style="color: gray; font-size:0.7em">Peter K. Dunn, Taryn Axelsen 2026: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></span></div>
  <div class="chapter-nav">
<div class="prev"><a href="ChapterTransformations.html"><span class="header-section-number">10</span> Transformations of random variables</a></div>
<div class="next"><a href="MultivariateExtensions.html"><span class="header-section-number">12</span> Expectations for multivariate distributions*</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#ChapMultivariate"><span class="header-section-number">11</span> Multivariate distributions*</a></li>
<li><a class="nav-link" href="#MultivariateIntroduction"><span class="header-section-number">11.1</span> Introduction</a></li>
<li><a class="nav-link" href="#Multivariate"><span class="header-section-number">11.2</span> Multivariate random variables and matrix notation</a></li>
<li><a class="nav-link" href="#RandomVectors"><span class="header-section-number">11.3</span> Random vectors</a></li>
<li><a class="nav-link" href="#MultivariateProbFn"><span class="header-section-number">11.4</span> Joint probability functions</a></li>
<li><a class="nav-link" href="#MultivariateDistFn"><span class="header-section-number">11.5</span> Joint distribution functions</a></li>
<li><a class="nav-link" href="#marginal-and-conditional-distributions"><span class="header-section-number">11.6</span> Marginal and conditional distributions</a></li>
<li><a class="nav-link" href="#MultivariateIndependence"><span class="header-section-number">11.7</span> Multivariate independence</a></li>
<li><a class="nav-link" href="#BVNormalDistribution"><span class="header-section-number">11.8</span> The bivariate normal distribution</a></li>
<li><a class="nav-link" href="#MultinomialDistribution"><span class="header-section-number">11.9</span> Multinomial distribution</a></li>
<li><a class="nav-link" href="#MultivariateExercises"><span class="header-section-number">11.10</span> Exercises</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/PeterKDunn/DistTheory/blob/main/11-Multivariate.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/PeterKDunn/DistTheory/edit/main/11-Multivariate.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>The Theory of Statistical Distributions</strong>" was written by Peter K. Dunn and Taryn Axelsen. It was last built on Last updated: 2026-03-17.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
